# Generated by Django 5.1 on 2024-09-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobileno',
            field=models.IntegerField(verbose_name='Mobile No'),
        ),
    ]
